default: &default
  adapter: mysql
  pool: 5
  username: global
  password:
  timeout: 5000

development:
  <<: *default
  database: lans_development

test:
  <<: *default
  database: lans_test

production:
  <<: *default
  database: lans_production
